version: 0.2

# Set an environment variable that can be used below in the build phase.
env:
  variables:
    TEST_VAR: "t2.micro"
phases:
  install:
    commands:
      - echo Entered the install phase
      - apt-get update -y
      - echo $TEST_VAR
      - echo $AWS_REGION
    finally:
      - echo This always runs even if the update or install commands fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - ls -altr
      - printenv
      - echo Entered the build phase...
      - echo Build started on 'date'
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...        
